# ======================================================
# CMAPSS Predictive Maintenance API
# Docker + MLOps
# Runtime: Python 3.10
# ======================================================

FROM python:3.10-slim

# ----------------------
# Environment settings
# ----------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# Reduce TensorFlow CPU noise / keep numerics stable
ENV TF_ENABLE_ONEDNN_OPTS=0

# ----------------------
# Working directory
# ----------------------
WORKDIR /app

# ----------------------
# System dependencies
# ----------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
  && rm -rf /var/lib/apt/lists/*

# ----------------------
# Python dependencies (Linux-locked)
# ----------------------
# IMPORTANT:
# - Do NOT use Windows lock inside Docker
# - Use infra/requirements.docker.lock.txt only
# ----------------------
COPY infra/requirements.docker.lock.txt /app/requirements.docker.lock.txt

RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
  && pip install --no-cache-dir -r /app/requirements.docker.lock.txt

# ----------------------
# Application code + configs
# ----------------------
COPY backend /app/backend
COPY configs /app/configs

# ----------------------
# Models handling
# ----------------------
# For Cloud Run CD  bake models into the image.
# This ensures the container has:
# /app/models/FD001/FD001_GRU_BASE_BEST.keras ... etc
#
# NOTE: Make sure `.dockerignore` is NOT excluding `models/`
RUN mkdir -p /app/models
COPY models /app/models
# ----------------------
# RAG index (Copilot)
# ----------------------
RUN mkdir -p /app/rag_index
COPY rag_index /app/rag_index

# ----------------------
# Swagger payloads 
RUN mkdir -p /app/samples/payloads
COPY samples/payloads/*.json /app/samples/payloads/


# ----------------------
# Expose API port
# ----------------------
# Cloud Run expects 8080 by default.
EXPOSE 8080

# ----------------------
# Start FastAPI
# ----------------------
# Cloud Run sets PORT env var at runtime (usually 8080).
# This keeps local default 8000 when PORT is not set.
CMD ["sh", "-lc", "uvicorn backend.api.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
